<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_Remember me_iCheck-helper</name>
   <tag></tag>
   <elementGuidId>8b5f65f4-ad1c-42a4-984f-1dc1fe6e2cc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ins.iCheck-helper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ins</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/form[@class=&quot;form-signin form-horizontal wow fadeIn animated animated&quot;]/div[1]/div[@class=&quot;row form-group&quot;]/div[@class=&quot;col-xs-6&quot;]/label[@class=&quot;checkbox hover&quot;]/div[@class=&quot;icheckbox_square-grey hover&quot;]/ins[@class=&quot;iCheck-helper&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins</value>
   </webElementXpaths>
</WebElementEntity>
